#!/usr/bin/env node

require('babel-core/register')({
    optional: [
        'es7.classProperties'
    ],
    loose: [
        'es6.modules',
        'es6.classes'
    ]
})

var argv = require( 'yargs' )
    .usage( 'Usage: $0 <bundle_path> [options]' )
    .demand( 1 )
    .option( 'o', {
        alias: 'output',
        demand: true,
        describe: 'Output path',
        type: 'string'
    })
    .options( 'd', {
        alias: 'debug',
        demand: false,
        describe: 'Shortcut to stick browserify into debug mode',
        type: 'boolean'
    })
    .argv

// @TODO sort this out
if ( argv.watch ) {
    require( './watcher' )( argv )
    return
}

require( './bundler' )( argv )
