#!/usr/bin/env node

require('babel-core/register')({
    optional: [
        'es7.classProperties'
    ],
    loose: [
        'es6.modules',
        'es6.classes'
    ],
    ignore: false,
    only: new RegExp( __dirname )

})

var argv = require( 'yargs' )
    .usage( 'Usage: $0 <bundle_path> [options]' )
    .demand( 1 )
    .option( 'o', {
        alias: 'output',
        demand: true,
        describe: 'Output path',
        type: 'string'
    })
    .option( 'd', {
        alias: 'debug',
        demand: false,
        describe: 'Shortcut to stick browserify into debug mode',
        type: 'boolean'
    })
    .option( 't', {
        alias: 'transform',
        demand: false,
        describe: 'Add transforms to the browserify pipeline',
        type: 'string'
    })
    .option( 'v', {
        alias: 'verbose',
        demand: false,
        describe: 'Adds extra logging, including timings',
        type: 'boolean'
    })
    .options( 'watch', {
        demand: false,
        describe: 'Starts watching for file changes, expects a glob',
        type: 'string'
    })
    .help( 'h' )
    .alias( 'h', 'help' )
    .argv

// @TODO sort this out
if ( argv.watch ) {
    var watcher = require( './watcher' )( argv )
    watcher.watch()
} else {
    var bundler = require( './bundler' )( argv )
    bundler.bundle()

}
